# Generated by Django 3.0.4 on 2020-03-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='Customer_id',
            field=models.IntegerField(null=True),
        ),
    ]
