# Generated by Django 3.0.4 on 2020-03-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20200309_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='Customer_Marital_status',
            field=models.CharField(choices=[(1, '1'), (0, '0')], max_length=5),
        ),
        migrations.AlterField(
            model_name='cars',
            name='Matt_finish',
            field=models.CharField(choices=[(1, '1'), (0, '0')], max_length=5),
        ),
        migrations.AlterField(
            model_name='cars',
            name='Power_steering',
            field=models.CharField(choices=[(1, '1'), (0, '0')], max_length=5),
        ),
        migrations.AlterField(
            model_name='cars',
            name='airbags',
            field=models.CharField(choices=[(1, '1'), (0, '0')], max_length=5),
        ),
        migrations.AlterField(
            model_name='cars',
            name='music_system',
            field=models.CharField(choices=[(1, '1'), (0, '0')], max_length=5),
        ),
        migrations.AlterField(
            model_name='cars',
            name='sunroof',
            field=models.CharField(choices=[(1, '1'), (0, '0')], max_length=5),
        ),
    ]
