# Generated by Django 3.0.4 on 2020-03-09 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20200309_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='SellingPrice',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
