# Generated by Django 3.0.4 on 2020-07-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20200725_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuboid',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
