# Generated by Django 3.0.4 on 2020-07-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20200725_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuboid',
            name='createdby',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
