# Generated by Django 3.0.4 on 2020-07-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_cuboid_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuboid',
            name='createdtime',
            field=models.DateField(null=True),
        ),
    ]
